# Generated by Django 4.0.4 on 2022-05-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_index_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
