# Generated by Django 4.0.4 on 2022-05-18 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_author_died'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(choices=[('CR', 'Crime'), ('ED', 'Education'), ('FA', 'Fantasy'), ('FI', 'Fiction'), ('NO', 'No genre'), ('NF', 'Non Fiction'), ('RO', 'Romance'), ('TH', 'Thriller')], default='NO', max_length=2)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'title'], name='index-author-title'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='uniqe-author-title-constraint'),
        ),
    ]
